name: 'Build Deb in Actions'
description: 'Build Debian deb file with ease!'
author: 'Elysia'

# Define your inputs here.
inputs:
  build-binary:
    description: '构建二进制 deb 文件 (目前尚不支持)'
    required: true
    default: ''
  build-source:
    description: '构建源代码包'
    required: true
    default: ''
  output-dir:
    description: '输出目录'
    required: false
    default: './output'
  source-dir:
    description: '源代码目录'
    required: false
    default: './source'
  git-ref-name:
    description: '用于构建 deb 文件的 Git 引用名称'
    required: false
    default: 'main'
    

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node22
  main: dist/index.js
